### ISSUE TITLE
Error installing pybloom

### ISSUE THREAD

**Issue by Minyanaing** [jaybaird/python-bloomfilter#36]
When doing the install, the following error is obtained.

`ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-iwa1sif6/pybloom/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-install-iwa1sif6/pybloom/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:`
                                            ^
    `SyntaxError: invalid syntax
    ----------------------------------------`
`ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-iwa1sif6/pybloom/`

Is there any way to solve the problem?

**Comment by vmkhlv** [comment]
@Minyanaing hi, you could probably use `pip install pybloom-live`(https://github.com/joseph-fox/python-bloomfilter)
