### ISSUE TITLE
How to install pybloom on mac os with python3?

### ISSUE THREAD

**Issue by akshat-khare** [jaybaird/python-bloomfilter#39]
I can't install pybloom on pip3

**Comment by todofixthis** [comment]
I'm not sure if my issue is related to yours, since you didn't provide any info about what's not working, but I suspect it's similar.

Using Python 3.7:
```
> pip install pybloom
Collecting pybloom
  Downloading https://files.pythonhosted.org/packages/1a/82/a1ad015bdc19bd7e10aa97070329b84b5e01c0c6b5de88df664a98413eed/pybloom-1.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: .virtualenvwrapper/bloom/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/setup.py'"'"'; __file__='"'"'/private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/pip-egg-info
         cwd: /private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "/private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Note that I can install the library successfully directly from the GitHub repo:
```
> pip install -e git+https://github.com/jaybaird/python-bloomfilter.git#egg=pybloom
Obtaining pybloom from git+https://github.com/jaybaird/python-bloomfilter.git#egg=pybloom
  Cloning https://github.com/jaybaird/python-bloomfilter.git to /Users/phx/.virtualenvwrapper/bloom/src/pybloom
  Running command git clone -q https://github.com/jaybaird/python-bloomfilter.git /Users/phx/.virtualenvwrapper/bloom/src/pybloom
Collecting bitarray>=0.3.4
  Downloading https://files.pythonhosted.org/packages/eb/fd/bf67cfea810305148ab8a1e8fbdcc5179f56979c73907fec9a36ebd4a58a/bitarray-1.2.0.tar.gz (48kB)
     |████████████████████████████████| 51kB 144kB/s
Building wheels for collected packages: bitarray
  Building wheel for bitarray (setup.py) ... done
  Created wheel for bitarray: filename=bitarray-1.2.0-cp37-cp37m-macosx_10_15_x86_64.whl size=46135 sha256=ad6e7225fb26dd3fd3823875e8a63a323d86a4656c52d1a8911fc92041e8120b
  Stored in directory: /Users/phx/Library/Caches/pip/wheels/7d/74/a0/a16a871bce5b38a192b8a529805d69abd4a28745ea31bc2ff1
Successfully built bitarray
Installing collected packages: bitarray, pybloom
  Running setup.py develop for pybloom
Successfully installed bitarray-1.2.0 pybloom
```

Possibly the error has to do with the way the source release was built for PyPI.  As a workaround I'm installing directly from GitHub.  This might or might not work for you, depending on what issue you're experiencing.

**Comment by sairoko12** [comment]
> I'm not sure if my issue is related to yours, since you didn't provide any info about what's not working, but I suspect it's similar.
> 
> Using Python 3.7:
> 
> ```
> > pip install pybloom
> Collecting pybloom
>   Downloading https://files.pythonhosted.org/packages/1a/82/a1ad015bdc19bd7e10aa97070329b84b5e01c0c6b5de88df664a98413eed/pybloom-1.1.tar.gz
>     ERROR: Command errored out with exit status 1:
>      command: .virtualenvwrapper/bloom/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/setup.py'"'"'; __file__='"'"'/private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/pip-egg-info
>          cwd: /private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/
>     Complete output (8 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/setup.py", line 2, in <module>
>         from ez_setup import use_setuptools
>       File "/private/var/folders/7p/nvh7s8wn3c1fx706zlcwl2d00000gn/T/pip-install-81j_rkgl/pybloom/ez_setup.py", line 98
>         except pkg_resources.VersionConflict, e:
>                                             ^
>     SyntaxError: invalid syntax
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ```
> 
> Note that I can install the library successfully directly from the GitHub repo:
> 
> ```
> > pip install -e git+https://github.com/jaybaird/python-bloomfilter.git#egg=pybloom
> Obtaining pybloom from git+https://github.com/jaybaird/python-bloomfilter.git#egg=pybloom
>   Cloning https://github.com/jaybaird/python-bloomfilter.git to /Users/phx/.virtualenvwrapper/bloom/src/pybloom
>   Running command git clone -q https://github.com/jaybaird/python-bloomfilter.git /Users/phx/.virtualenvwrapper/bloom/src/pybloom
> Collecting bitarray>=0.3.4
>   Downloading https://files.pythonhosted.org/packages/eb/fd/bf67cfea810305148ab8a1e8fbdcc5179f56979c73907fec9a36ebd4a58a/bitarray-1.2.0.tar.gz (48kB)
>      |████████████████████████████████| 51kB 144kB/s
> Building wheels for collected packages: bitarray
>   Building wheel for bitarray (setup.py) ... done
>   Created wheel for bitarray: filename=bitarray-1.2.0-cp37-cp37m-macosx_10_15_x86_64.whl size=46135 sha256=ad6e7225fb26dd3fd3823875e8a63a323d86a4656c52d1a8911fc92041e8120b
>   Stored in directory: /Users/phx/Library/Caches/pip/wheels/7d/74/a0/a16a871bce5b38a192b8a529805d69abd4a28745ea31bc2ff1
> Successfully built bitarray
> Installing collected packages: bitarray, pybloom
>   Running setup.py develop for pybloom
> Successfully installed bitarray-1.2.0 pybloom
> ```
> 
> Possibly the error has to do with the way the source release was built for PyPI. As a workaround I'm installing directly from GitHub. This might or might not work for you, depending on what issue you're experiencing.

I have the same problem, but your solution works fine to me. Thanks a lot

**Comment by alessmithxx** [comment]
apt list --upgradable
